services:
  frontend:
    build:
      context: G:/assessment_reunion/frontend 
    image: avyakta000/flamingo-client-1:0.0.2
    ports:
      - "3000:80"
      - "3001:443"  
    networks:
      - app-network
      - assessment_app_network  

    # command: ["nginx", "-g", "daemon off;"]
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  #  needed in production
    #   - ./nginx/conf.d/client.conf:/etc/nginx/conf.d/default.conf:ro  #  needed in production


  fastapi:
    build:
      context: G:/graphql/server  
    image: avyakta000/flamingo-microserver:0.0.0  
    ports:
      - "8000:8000" 
    networks:
      - app-network
      - assessment_app_network  
    environment:
      - WORKERS=4
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "app.main:app"]

networks:
  app-network:
    driver: bridge
    internal: true  
  assessment_app_network:
    external: true  

